config/routes.rb
Rails.application.routes.draw do
  resources :properties
  # Devise
  devise_for :users,  controllers: { registrations: 'registrations' },
                      path: '',
                      path_names: { sign_in: 'login',
                                    sign_out: 'logout',
                                    sign_up: 'register' }
  resources :contacts, only: %i[new create]
      get '/home',    to: 'pages#home'
      get '/privacy', to: 'pages#privacy'
      get '/legal',   to: 'pages#terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :bigint           not null, primary key
#  name       :string
#  email      :string
#  message    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Contact < ApplicationRecord
      validates :name,    presence: true
  	validates :email,   presence: true,
                      format: { with: URI::MailTo::EMAIL_REGEXP }
  	validates :message, presence: true

end

app/models/feature.rb
# == Schema Information
#
# Table name: features
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Feature < ApplicationRecord
      validates :name, presence: true, uniqueness: true
end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id               :bigint           not null, primary key
#  user_id          :bigint           not null
#  type_offer_id    :bigint           not null
#  type_property_id :bigint           not null
#  area             :integer
#  description      :text
#  price            :decimal(, )
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :type_offer
  belongs_to :type_property
end

app/models/property_feature.rb
class PropertyFeature < ApplicationRecord
  belongs_to :property
  belongs_to :feature
end

app/models/type_offer.rb
# == Schema Information
#
# Table name: type_offers
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class TypeOffer < ApplicationRecord
      validates :name, presence: true, uniqueness: true
end

app/models/type_property.rb
class TypeProperty < ApplicationRecord
      validates :name, presence: true, uniqueness: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  name                   :string
#  phone                  :bigint
#  role                   :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validaciones
         validates :name, presence: true
         validates :phone, presence: true
         enum role: [:regular, :admin]

  # Relaciones
         has_many :property_features, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
      def new
            @contact = Contact.new
      end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # DELETE /contacts/1 or /contacts/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def terms
  end

  def privacy
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:user_id, :type_offer_id, :type_property_id, :area, :description, :price)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
      before_action :configure_permitted_parameters, if: :devise_controller?
      protect_from_forgery with: :exception
    
      protected
    
      def configure_permitted_parameters
        added_attrs = %i[ email password password_confirmation remember_me name phone role ]
    
        devise_parameter_sanitizer.permit :sign_up, keys: %i[email password password_confirmation name phone]
        devise_parameter_sanitizer.permit :sign_in, keys: %i[email password remember_me]
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      end
    
      def update_resource(resource, params)
        resource.update_without_password(params)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inforcaphouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
	<li>
      <%= link_to "Políticas de privacidad", privacy_path %>
    </li>
    <li>
      <%= link_to "Terminos y condiciones", legal_path %>
    </li>
</ul>
</nav>  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :type_offer_id, style: "display: block" %>
    <%= form.text_field :type_offer_id %>
  </div>

  <div>
    <%= form.label :type_property_id, style: "display: block" %>
    <%= form.text_field :type_property_id %>
  </div>

  <div>
    <%= form.label :area, style: "display: block" %>
    <%= form.number_field :area %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <p>
    <strong>User:</strong>
    <%= property.user_id %>
  </p>

  <p>
    <strong>Type offer:</strong>
    <%= property.type_offer_id %>
  </p>

  <p>
    <strong>Type property:</strong>
    <%= property.type_property_id %>
  </p>

  <p>
    <strong>Area:</strong>
    <%= property.area %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= property.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= property.price %>
  </p>

</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Properties</h1>

<div id="properties">
  <% @properties.each do |property| %>
    <%= render property %>
    <p>
      <%= link_to "Show this property", property %>
    </p>
  <% end %>
</div>

<%= link_to "New property", new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>

<div>
  <%= link_to "Edit this property", edit_property_path(@property) %> |
  <%= link_to "Back to properties", properties_path %>

  <%= button_to "Destroy this property", @property, method: :delete %>
</div>